apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: aanshojha/flask-login-app:latest
        env: 
          - name: MYSQL_HOST
            value: 'mysqldb'   # Use service name instead of 'localhost'
          - name: MYSQL_USER
            value: 'root'
          - name: MYSQL_ROOT_PASSWORD
            value: 'password'
          - name: FULLSTACK_DB
            value: 'full_stack'
          - name: FULLSTACK_CRED_TABLE
            value: 'creds'
        ports: 
          - containerPort: 5000  # Flask app port

      - name: mysqldb
        image: mysql:latest
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: 'password'
        ports: 
          - containerPort: 3306  # MySQL port
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
  selector: 
    matchLabels:
      app: flask-app
