apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector: 
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysqldb
          image: mysql:latest
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                configMapKeyRef:
                  name: flask-config
                  key: MYSQL_ROOT_PASSWORD
          ports: 
            - containerPort: 3306  # MySQL port
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector: 
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: aanshojha/flask-login-app:latest
        env: 
          - name: EMAIL_ID
            valueFrom: 
              configMapKeyRef:
                name: flask-config
                key: EMAIL_ID
          - name: EMAIL_PASS
            valueFrom: 
              configMapKeyRef:
                name: flask-config
                key: EMAIL_PASS
          - name: MYSQL_HOST
            valueFrom: 
              configMapKeyRef:
                name: flask-config
                key: MYSQL_HOST
          - name: MYSQL_USER
            valueFrom: 
              configMapKeyRef:
                name: flask-config
                key: MYSQL_USER
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              configMapKeyRef:
                name: flask-config
                key: MYSQL_ROOT_PASSWORD
          - name: FULLSTACK_DB
            valueFrom: 
              configMapKeyRef:
                name: flask-config
                key: FULLSTACK_DB
          - name: FULLSTACK_CRED_TABLE
            valueFrom: 
              configMapKeyRef:
                name: flask-config
                key: FULLSTACK_CRED_TABLE
        ports: 
          - containerPort: 5000  # Flask app port