version: '3.8'
services:
  mysql_cn:
    image: mysql:latest
    env_file:
      - .\.env
    networks:
      - aansh-net
    container_name: mysql_cn
    volumes:    # This is to persist credentials data (named volume)
      - aansh:/var/lib/mysql

  flask-app:
    build: .\
    restart: always # Very important, otherwise mysql container will not be able to connect to flask-app
    depends_on:
      - mysql_cn
    ports:
      - "80:80"
    env_file:
      - .\.env
    networks:
      - aansh-net
    container_name: flask-app

networks:
  aansh-net:
    name: aansh-net

volumes:
  aansh: