version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - aansh-net 
    container_name: mysqldb
    volumes:
      - aansh:/var/lib/mysql

  flask-app:
    build: .\
    restart: always
    depends_on:
      - mysqldb
    ports:
      - "5000:5000"
    env_file:
      - .\.env
    networks:
      - aansh-net
    container_name: flask-app 

networks:
  aansh-net:
    name: aansh-net

volumes:
  aansh: