version: '3.8'
services:
  mysql_cn:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - aansh-net
    container_name: mysql_cn
    volumes:
      - aansh:/var/lib/mysql

  flask-app:
    build: .\
    restart: always # Very important otherwise be ready for hairloss
    depends_on:
      - mysql_cn
    ports:
      - "80:80"
    env_file:
      - .\.env
    networks:
      - aansh-net
    container_name: flask-app

networks:
  aansh-net:
    name: aansh-net

volumes:
  aansh: